title: Haoxian's Homepage
page-top-title: Haoxian Liang
top-section-bg-text: Be what you wanna be
home-subtitle: Haoxian Liang&ensp;|&ensp;梁浩贤
copyright-text: '&copy; Haoxian Liang 2025-2026. All Rights Reserved.'
